jobs:
  - job: ${{ parameters.name }}
    displayName: CI build for ${{ parameters.displayName }}

    pool:
      vmImage: ${{ parameters.vmImage }}

    dependsOn:
      - BuildAndTestsOnWindows
      - BuildAndTestsOnLinux

    steps:
      - checkout: self
        clean: true
        lfs: true

      - task: UseDotNet@2
        displayName: Use .NET Core SDK ${{ parameters.dotNetCoreVersion }}
        inputs:
          version: ${{ parameters.dotNetCoreVersion }}

      - powershell: dotnet tool install --tool-path ./tools --version ${{ parameters.cakeVersion }} Cake.Tool
        displayName: Setup prerequisites

      - powershell: ./tools/dotnet-cake --target=Sonar
        displayName: Sonar
        env:
          SONARCLOUD_TOKEN: $(sonarcloud.token)

      - powershell: ./tools/dotnet-cake --target=Publish
        displayName: Publish
        env:
          FEED_APIKEY: $(feed.apikey)
