version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  reviewers:
  - HofmeisterAn
  assignees:
  - HofmeisterAn
  ignore:
  - dependency-name: "*"
    versions:
    - ">= 0"
