name: $(date:yyyyMMdd)$(rev:.r)

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  dotNetCoreVersion: 3.1.102
  cakeVersion: 0.37.0

trigger:
  - master
  - develop
  - bugfix/*
  - feature/*

pr:
  - master
  - develop

jobs:
  # Run Windows build and tests.
  - template: azure/build.yml
    parameters:
      name: BuildAndTestsOnWindows
      displayName: Windows
      vmImage: windows-2019
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers.Tests.Unit.Containers.Windows

  # Run Unix build and tests.
  - template: azure/build.yml
    parameters:
      name: BuildAndTestsOnUnix
      displayName: Unix
      vmImage: ubuntu-18.04
      dotNetCoreVersion: $(dotNetCoreVersion)
      cakeVersion: $(cakeVersion)
      testFilter: FullyQualifiedName~DotNet.Testcontainers

  # Run static code analysis and publish artifact.
  - ${{ if in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/develop') }}:
    - template: azure/publish.yml
      parameters:
        name: Release
        displayName: Release
        vmImage: ubuntu-18.04
        dotNetCoreVersion: $(dotNetCoreVersion)
        cakeVersion: $(cakeVersion)
